doc_profile= char ('Zara Ali','Sr. surgeon', ...
    'RN Tagore Research center')
doc_profile =['Zara Ali     '; ...
               'sr.surgeon  '; ...
               'RN Tagore cardiology Hospital' 